### ISSUE TITLE
George is 1D Only?

### ISSUE THREAD

**Issue by scopatz** [dfm/george#41]
Hello, This is more of a question than anything, but it seems that George only handles 1-dimensional inputs and responses. Is this true?  It seems like the `sklearn.gaussian_process` module does handle N-dim inputs and repsonses.  Is this true? I am new to the GP would and trying to get a handle on what the different tools and their limitations are. Thanks!

**Comment by shoyer** [comment]
George can definitely handle multi-dimensional Gaussian processes -- I've used it for 2D data in the past.  But the HODLR solver doesn't work terribly well for higher dimensional data, so in practical terms there is not going to be big difference in terms of performance between George and Scikit-Learn. Both will be limited by the speed of a Cholesky decomposition with SciPy.

**Comment by scopatz** [comment]
Thanks @shoyer - are there any examples that you can point me to that are for >1D?

**Comment by shoyer** [comment]
Here's a scratch work notebook that I was playing around with: https://gist.github.com/shoyer/80aa06f5ad44aacd9187

I haven't run this on a recent version of george though, so you'll probably have to do some futzing to get it working.

**Comment by scopatz** [comment]
Ahh Thanks a ton @shoyer. I had missed the ndim argument to the kernels. That is why nothing was working before. Also, it seems that the response (y, predicted dimension, whatever) must be one dimensional. I get a `ValueError: The predicted dimension must be 1-D` if it isn't when I call `gp.optimize()`. I guess that this is not such a big deal because for every thing that one wishes to predict, you can just re-run `gp.optimize()` with a different vector.

**Comment by scopatz** [comment]
As an aside, the running emcee here just seems to hang indefinitely. That doesn't seem to be the case with the notebook you shared where it took less than a minute. Not sure what is going on there but I am on the latest emcee (v2.1.0)

**Comment by astromark** [comment]
Hi shoyer, I'm not sure I quite follow your example. In my case I'm working with a 432x432 image. What should I be giving to gp.compute?

**Comment by astromark** [comment]
Ahh, I see. That's a very good point. Thanks for the link.

**Comment by EskreisWinkler** [comment]
I tried using george for 2d data and the computation of the gp seems to work fine, but the get_matrix function appears to only work in 1d. Since the kernel matrix is the same size no matter the dimension of the data I am surprised I am getting an error for this. Specifically, the error I am getting is:

>>> gp.get_matrix(range(len(x)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/george/gp.py", line 365, in get_matrix
    r, _ = self.parse_samples(t, False)
  File "/Users/jonathaneskreis-winkler/anaconda/lib/python3.6/site-packages/george/gp.py", line 132, in parse_samples
    raise ValueError("Dimension mismatch")
ValueError: Dimension mismatch

**Comment by dfm** [comment]
If you're using a 2-D, your input to `get_matrix` needs to be the right shape! e.g.

```
gp.get_matrix(np.random.rand(len(x), 2))
```

will work.

**Comment by EskreisWinkler** [comment]
Isn’t the matrix a len(x)Xlen(x) object?

On Feb 13, 2017, at 2:33 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're using a 2-D, your input to get_matrix needs to be the right shape! e.g.

gp.get_matrix(np.random.rand(len(x), 2))


will work.

**Comment by EskreisWinkler** [comment]
i.e. no matter what dimension? I had thought I am just providing indices of the data points I’m interested in?

On Feb 13, 2017, at 2:36 PM, Jonathan Eskreis-Winkler <eskreiswinkler@uchicago.edu<mailto:eskreiswinkler@uchicago.edu>> wrote:

Isn’t the matrix a len(x)Xlen(x) object?

On Feb 13, 2017, at 2:33 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're using a 2-D, your input to get_matrix needs to be the right shape! e.g.

gp.get_matrix(np.random.rand(len(x), 2))


will work.

**Comment by dfm** [comment]
Nope. It's the _coordinates_ of the points: http://dan.iel.fm/george/current/user/gp/#george.GP.sample

**Comment by EskreisWinkler** [comment]
Oh wow. Thank you for clarifying.

Is there any way to directly query the entries of the factorization, if all the terms were multiplied together? I am really interested in evaluating the properties of the factorization at the matrix approximation level.

On Feb 13, 2017, at 2:42 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope. It's the coordinates of the points: http://dan.iel.fm/george/current/user/gp/#george.GP.sample

**Comment by EskreisWinkler** [comment]
Or perhaps I can just query with the coordinates of the data that I used to form the gp object and get what their corresponding kernel matrix approximation is?

On Feb 13, 2017, at 2:44 PM, Jonathan Eskreis-Winkler <eskreiswinkler@uchicago.edu<mailto:eskreiswinkler@uchicago.edu>> wrote:

Oh wow. Thank you for clarifying.

Is there any way to directly query the entries of the factorization, if all the terms were multiplied together? I am really interested in evaluating the properties of the factorization at the matrix approximation level.

On Feb 13, 2017, at 2:42 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


Nope. It's the coordinates of the points: http://dan.iel.fm/george/current/user/gp/#george.GP.sample

**Comment by dfm** [comment]
Unfortunately that's not exposed to the Python code. If you're using the HODLR solver then it never actually constructs the full matrix (that's why it can be faster than N^2!) but if there's something inside of [HODLR](https://github.com/sivaramambikasaran/HODLR/tree/master/header) that you'd like to see exposed, let me know.

If you're just using the basic solver then the factorized matrix is [stored in the `_factor` attribute of the solver object](https://github.com/dfm/george/blob/master/george/basic.py#L69).

Hope that helps!

**Comment by EskreisWinkler** [comment]
But if “data” was the variable used to form the covariance matrix of the GP, would querying the “nsamples” located at “data” coordinates be equivalent to extracting the matrix?

On Feb 13, 2017, at 3:35 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately that's not exposed to the Python code. If you're using the HODLR solver then it never actually constructs the full matrix (that's why it can be faster than N^2!) but if there's something inside of HODLR<https://github.com/sivaramambikasaran/HODLR/tree/master/header> that you'd like to see exposed, let me know.

If you're just using the basic solver then the factorized matrix is stored in the _factor attribute of the solver object<https://github.com/dfm/george/blob/master/george/basic.py#L69>.

Hope that helps!

**Comment by scopatz** [comment]
Also, I think we can go ahead and close this issue whenever @dfm feels it is ready.

**Comment by dfm** [comment]
@scopatz: will do 😄 

@EskreisWinkler: if you use `K = gp.get_matrix(x)` where `x` is the array of input coordinates of your data then `K` will be _almost_ the matrix that is used in the likelihood calculation. If you want to include the `yerr` term from `compute` then you'll need to do something like:

```
K = gp.get_matrix(x)
K[np.diag_indices_from(K)] += yerr**2
```

**Comment by EskreisWinkler** [comment]
Excellent. Thanks so much for your quick and thorough feedback!

On Feb 13, 2017, at 3:44 PM, Dan Foreman-Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


@scopatz<https://github.com/scopatz>: will do 😄

@EskreisWinkler<https://github.com/EskreisWinkler>: if you use K = gp.get_matrix(x) where x is the array of input coordinates of your data then K will be almost the matrix that is used in the likelihood calculation. If you want to include the yerr term from compute then you'll need to do something like:

K = gp.get_matrix(x)
K[np.diag_indices_from(K)] += yerr**2
