### ISSUE TITLE
MemoryError when computing grad_lnlikelihood with HODLR

### ISSUE THREAD

**Issue by transientlunatic** [dfm/george#50]
When trying to calculate the grad_lnlikelihood method of a large Gaussian process on the 1.0.0dev branch I get thrown a memory error. 

Below's a minimum (not) working example which replicates the problem on my system; on a system with a much larger amount of memory I've been able to increase past ~4000 samples, but isn't this problem meant to be avoided by using the HODLR solver?

```
import numpy
import george
from george import kernels

training_x = np.random.rand(4000, 9)
training_y = np.random.rand(4000, 1)

k0 =  np.std(training_y)**2
k3 = kernels.Matern52Kernel(np.ones(9), ndim=9)

kernel = k0+k3
gp = george.GP(kernel, tol=1e-6, solver=george.HODLRSolver)

gp.compute(training_x)

gp.grad_lnlikelihood(training_y.T[0])
```
The traceback I get is

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-423-f8304806f185> in <module>()
     14 gp.compute(training_x)
     15 
---> 16 gp.grad_lnlikelihood(training_y.T[0])

/home/daniel/.virtualenvs/heron/local/lib/python2.7/site-packages/george-1.0.0.dev0-py2.7-linux-x86_64.egg/george/gp.pyc in grad_lnlikelihood(self, y, quiet)
    453         if self.fit_kernel and len(self.kernel):
    454             l = len(self.kernel)
--> 455             Kg = self.kernel.get_gradient(self._x)
    456             grad[n:n+l] = 0.5 * np.einsum("ijk,ij", Kg, A)
    457 

/home/daniel/.virtualenvs/heron/local/lib/python2.7/site-packages/george-1.0.0.dev0-py2.7-linux-x86_64.egg/george/kernels.pyc in get_gradient(self, x1, x2)
    204             x2 = np.ascontiguousarray(x2, dtype=np.float64)
    205             g = self.kernel.gradient_general(which, x1, x2)
--> 206         return g[:, :, self.unfrozen]
    207 
    208     def test_gradient(self, x1, x2=None, eps=1.32e-6, **kwargs):

MemoryError: 
```

**Comment by dfm** [comment]
The problem here is that the gradient calculation must compute the derivative of every element of the matrix wrt the parameters so this will be a 4000x4000x10 array of doubles. This probably wouldn't throw an error except I expect that numpy is copying the array in that last step. The gradient calculation uses HODLR to compute K^{-1} (like it does for `log_likelihood`) but not dK/dTheta. There might be a way to also exploit the approximate solver for this but, unfortunately, I don't think that it's going to be trivial!
