### ISSUE TITLE
Incorrect determinant with HODLR solver when kernel is diagonal

### ISSUE THREAD

**Issue by ideasrule** [dfm/george#60]
Sometimes, when only a WhiteKernel is used, lnlikelihood returns a nonsensical result.  This is due to a bug in HODLR, which was fixed in https://github.com/sivaramambikasaran/HODLR/pull/11

**Comment by dfm** [comment]
I updated the title to be a little more descriptive and less aggressive because I don't think that you meant to be so rude 😄!

This should now be fixed on the master branch. Please feel free to close or comment when you test the update.

I would also like to go on to say that it's not a great idea to use the WhiteKernel all by itself because you could implement that likelihood function substantially faster without inverting this full diagonal matrix!
