### ISSUE TITLE
Motivation behind optimization method removal

### ISSUE THREAD

**Issue by jbkalmbach** [dfm/george#81]
Hi @dfm,

I was just wondering what the motivation was for removing the simple optimization method in `george` v0.3 that was included in v0.2? I've written my own version of it for my project and assume most people using `george` will want to optimize hyperparameters.

**Comment by dfm** [comment]
It's really too hard to write a general purpose optimization routine that will work reliably on most problems. I've found that it's really better to require users to call the optimization routine themselves so that people actually know what's going on. That way, when things inevitably fail, there's a better chance that people will figure it out :-)
